### ISSUE TITLE
[Feature Request] Make translators "inline" property configurable

### ISSUE THREAD

**Issue by k0d13** [Wakeful-Cloud/html-translator#1]
Right now, inline anchors/links are placed on a new line.

HTML: 
![html](https://user-images.githubusercontent.com/40654585/168737456-07a24b0e-1eab-4904-95a3-dbc40cf11a9b.PNG)

Markdown:
![md](https://user-images.githubusercontent.com/40654585/168737459-2661e4fe-976f-4ffe-b329-2249bbd2d780.PNG)

What I am requesting is to add the ability to make anchors remain inline, as putting them on new line can make the final markdown unnecessarily messy and bulky, especially when the inputted HTML is only a few words/one sentence.

**Comment by Wakeful-Cloud** [comment]
Fixed - please upgrade to V1.1.2
